name: mcm_site
description: ""

version: 0.1.0

publish_to: "none"

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_math_fork: ^0.7.4
  go_router: ^14.8.0

  # Model serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2


flutter:
  uses-material-design: true
